[project]
name = "gcp-databricks-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-beam[gcp]>=2.65.0",
    "faker>=37.3.0",
    "pip>=25.1.1",
]
